---
- name: Merge CE configurations
  hosts: ce
  gather_facts: no
  vars_files:
  - ~/Secure/passwords
  tasks:
    - name: Merge configs
      ios_config:
        src: ./configs/{{ inventory_hostname }}.conf
        diff_against: running
        defaults: no
        backup: yes
      register: changes
    - debug: var=changes

- name: Merge PE configurations
  hosts: pe
  gather_facts: no
  vars_files:
  - ~/Secure/passwords
  tasks:
    - name: Merge configs
      ios_config:
        src: ./configs/{{ inventory_hostname }}.conf
        diff_against: running
        defaults: no
        backup: yes
      register: changes
    - debug: var=changes