---
- name: Retrieve OSPF neighbor information
  hosts: pe
  gather_facts: no
  vars_files:
  - ~/Secure/passwords
  tasks:
    - name: show ip ospf neighbor on all PEs
      ios_command:
        commands: 'show ip ospf neighbor'
      register: ospf_printout

    - name: Parse ospf_printout and convert to datastructure
      set_fact: ospf_neighbors="{{ ospf_printout.stdout[0] | parse_cli('parse_ios_ospf_neighbors.yml') }}"

    - name: Loop through OSPF neighbors and look for ones that are not UP
      debug:
        msg: "{{ inventory_hostname }}: {{ item.id }} is in state {{ item.state }}"
      with_items: "{{ ospf_neighbors.neighbors }}"
      when: item.up != true

    - name: show ip bgp vpnv4 all summary on all PEs
      ios_command:
        commands: 'show ip bgp vpnv4 all summary'
      register: bgp_printout

    - name: Parse bgp_printout and convert to datastructure
      set_fact:
        bgp_neighbors: "{{ bgp_printout.stdout[0] | parse_cli('parse_ios_bgp_summary.yml') }}"

    - name: Loop through BGP neighbors and look for ones that are not UP
      debug:
        msg: "{{ inventory_hostname }}: {{ item.neighbor }} is in state {{ item.state_or_nprefix }}"
      with_items: "{{ bgp_neighbors.neighbors }}"
      when: item.up != true
