---
g_bgp_asn: 65500
g_pe_mgmt_int_global: Lo100
g_pe_mgmt_int_gwan: Lo1
g_ospf_int1_ip_ospf_hello_interval: 10
g_ospf_int1_ip_subnet: 10.229.0.0/24
g_ospf_int1_mtu: 8900
g_ospf_process_id: 1
g_ospf_timers_spf_throttle_1: 5
g_ospf_timers_spf_throttle_2: 1000
g_ospf_timers_spf_throttle_3: 32000