---
- name: Retrieve 'show interface transciever details' data
  hosts: nxos
  gather_facts: no
  connection: local
  vars_files:
  - ~/Secure/passwords
  tasks:
  - nxos_command:
      commands: show interface transceiver details
    register: result
  - file: path=./output/stdout.raw state=absent
  - file: path=./output/stdout.raw state=touch
  - copy: content="{{ result.stdout[0] }}" dest=./output/stdout.raw
